export const treatmentCategories = [
  "nonSurgical",
  "face",
  "body",
  "breast",
];

export const treatments = [
  {
    key: "botox",
    category: "nonSurgical",
    profile: "botox",
    image: "/images/treatments/botox.png",
    sourceUrl: "https://botoksuygulamasiislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "botoks",
      en: "botox",
      de: "botox",
      he: "botox",
      fr: "botox",
      ar: "botox",
      it: "botox",
      es: "botox",
      zh: "botox",
    },
  },
  {
    key: "filler",
    category: "nonSurgical",
    profile: "filler",
    image: "/images/treatments/filler.png",
    sourceUrl: "https://dolguuygulamasiislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "dolgu",
      en: "dermal-filler",
      de: "filler",
      he: "dermal-filler",
      fr: "injection-acide-hyaluronique",
      ar: "dermal-filler",
      it: "filler",
      es: "relleno-dermico",
      zh: "dermal-filler",
    },
  },
  {
    key: "mesotherapy",
    category: "nonSurgical",
    profile: "mesotherapy",
    image: "/images/treatments/mesotherapy.png",
    sourceUrl: "https://mezoterapigenclikasisiislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "mezoterapi-genclik-asisi",
      en: "mesotherapy-skin-booster",
      de: "mesotherapie-skinbooster",
      he: "mesotherapy-skin-booster",
      fr: "mesotherapie-skinbooster",
      ar: "mesotherapy-skin-booster",
      it: "mesoterapia-skinbooster",
      es: "mesoterapia-skinbooster",
      zh: "mesotherapy-skin-booster",
    },
  },
  {
    key: "rhinoplasty",
    category: "face",
    profile: "rhinoplasty",
    image: "/images/treatments/rhinoplasty.png",
    sourceUrl: "https://burunestetigiislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "burun-estetigi",
      en: "rhinoplasty",
      de: "nasenkorrektur",
      he: "rhinoplasty",
      fr: "rhinoplastie",
      ar: "rhinoplasty",
      it: "rinoplastica",
      es: "rinoplastia",
      zh: "rhinoplasty",
    },
  },
  {
    key: "upperEyelid",
    category: "face",
    profile: "eyelid",
    image: "/images/treatments/upper-eyelid.png",
    sourceUrl: "https://ustgozkapagiameliyatiislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "ust-goz-kapagi",
      en: "upper-eyelid-surgery",
      de: "oberlidstraffung",
      he: "upper-eyelid-surgery",
      fr: "blepharoplastie-superieure",
      ar: "upper-eyelid-surgery",
      it: "blefaroplastica-superiore",
      es: "blefaroplastia-superior",
      zh: "upper-eyelid-surgery",
    },
  },
  {
    key: "thighLift",
    category: "body",
    profile: "bodySurgery",
    image: "/images/treatments/thigh-lift.png",
    sourceUrl: "http://bacakuylukgermeislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "bacak-uyluk-germe",
      en: "thigh-lift",
      de: "oberschenkelstraffung",
      he: "thigh-lift",
      fr: "lifting-cuisses",
      ar: "thigh-lift",
      it: "lifting-cosce",
      es: "lifting-muslos",
      zh: "thigh-lift",
    },
  },
  {
    key: "bblLiposuction",
    category: "body",
    profile: "bodySurgery",
    image: "/images/treatments/bbl-liposuction.png",
    sourceUrl: "https://bblpopoliposuctionislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "bbl-popo-liposuction",
      en: "bbl-liposuction",
      de: "bbl-liposuktion",
      he: "bbl-liposuction",
      fr: "bbl-liposuccion",
      ar: "bbl-liposuction",
      it: "bbl-liposuzione",
      es: "bbl-liposuccion",
      zh: "bbl-liposuction",
    },
  },
  {
    key: "tummyTuck",
    category: "body",
    profile: "bodySurgery",
    image: "/images/treatments/tummy-tuck.png",
    sourceUrl: "https://karingermeislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "karin-germe",
      en: "tummy-tuck",
      de: "bauchdeckenstraffung",
      he: "tummy-tuck",
      fr: "abdominoplastie",
      ar: "tummy-tuck",
      it: "addominoplastica",
      es: "abdominoplastia",
      zh: "tummy-tuck",
    },
  },
  {
    key: "tummyTuckLiposuction",
    category: "body",
    profile: "bodySurgery",
    image: "/images/treatments/tummy-tuck-liposuction.png",
    sourceUrl: "https://karingermeliposuctionislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "karin-germe-liposuction",
      en: "tummy-tuck-liposuction",
      de: "bauchdeckenstraffung-liposuktion",
      he: "tummy-tuck-liposuction",
      fr: "abdominoplastie-liposuccion",
      ar: "tummy-tuck-liposuction",
      it: "addominoplastica-liposuzione",
      es: "abdominoplastia-liposuccion",
      zh: "tummy-tuck-liposuction",
    },
  },
  {
    key: "armLift",
    category: "body",
    profile: "bodySurgery",
    image: "/images/treatments/arm-lift.png",
    sourceUrl: "https://kolgermeislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "kol-germe",
      en: "arm-lift",
      de: "armstraffung",
      he: "arm-lift",
      fr: "lifting-bras",
      ar: "arm-lift",
      it: "lifting-braccia",
      es: "lifting-brazos",
      zh: "arm-lift",
    },
  },
  {
    key: "liposuction",
    category: "body",
    profile: "bodySurgery",
    image: "/images/treatments/liposuction.png",
    sourceUrl: "https://liposuctionislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "liposuction",
      en: "liposuction",
      de: "liposuktion",
      he: "liposuction",
      fr: "liposuccion",
      ar: "liposuction",
      it: "liposuzione",
      es: "liposuccion",
      zh: "liposuction",
    },
  },
  {
    key: "breastLift",
    category: "breast",
    profile: "breastSurgery",
    image: "/images/treatments/breast-lift.png",
    sourceUrl: "https://memediklestirmeestetigiislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "meme-diklestirme",
      en: "breast-lift",
      de: "bruststraffung",
      he: "breast-lift",
      fr: "lifting-mammaire",
      ar: "breast-lift",
      it: "mastopessi",
      es: "mastopexia",
      zh: "breast-lift",
    },
  },
  {
    key: "breastLiftImplant",
    category: "breast",
    profile: "breastSurgery",
    image: "/images/treatments/breast-lift-implant.png",
    sourceUrl: "https://memediklestirmeprotezestetigiislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "meme-diklestirme-protez",
      en: "breast-lift-implants",
      de: "bruststraffung-implantate",
      he: "breast-lift-implants",
      fr: "lifting-mammaire-implants",
      ar: "breast-lift-implants",
      it: "mastopessi-protesi",
      es: "mastopexia-implantes",
      zh: "breast-lift-implants",
    },
  },
  {
    key: "breastImplant",
    category: "breast",
    profile: "breastSurgery",
    image: "/images/treatments/breast-implant.png",
    sourceUrl: "https://memeproteziislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "meme-protezi",
      en: "breast-implants",
      de: "brustimplantate",
      he: "breast-implants",
      fr: "implants-mammaires",
      ar: "breast-implants",
      it: "protesi-mammarie",
      es: "implantes-mamarios",
      zh: "breast-implants",
    },
  },
  {
    key: "breastReduction",
    category: "breast",
    profile: "breastSurgery",
    image: "/images/treatments/breast-reduction.png",
    sourceUrl: "https://memekucultmeislemsonrasi.britishestetik.com/",
    slugs: {
      tr: "meme-kucultme",
      en: "breast-reduction",
      de: "brustverkleinerung",
      he: "breast-reduction",
      fr: "reduction-mammaire",
      ar: "breast-reduction",
      it: "riduzione-mammaria",
      es: "reduccion-mamaria",
      zh: "breast-reduction",
    },
  },
];

export function getTreatmentsByCategory(category) {
  return treatments.filter((treatment) => treatment.category === category);
}

export function getTreatmentBySlug(locale, slug) {
  return treatments.find((treatment) => treatment.slugs[locale] === slug);
}

export function getTreatmentByAnySlug(slug) {
  return treatments.find((treatment) => Object.values(treatment.slugs).includes(slug));
}

export function getTreatmentHref(treatment, locale) {
  return {
    pathname: "/treatments/[slug]",
    params: { slug: treatment.slugs[locale] },
  };
}
